### ISSUE TITLE
希望能够及时更新啊

### ISSUE THREAD

**Issue by leoxiaoping** [musicode/react-native-pure-xinge-push#1]
希望能够及时更新啊，没原生native 代码工程师 换了三个了，被坑哭了

**Comment by musicode** [comment]
难道不是最新的吗？

**Comment by leoxiaoping** [comment]
我说其他的坑，你这个是最新的！

**Comment by musicode** [comment]
如果不是别的太坑，我也不会自己搞一个。。。

**Comment by leoxiaoping** [comment]
@musicode  兄台在北京哪高就，有空请你吃饭

**Comment by musicode** [comment]
请我吃饭就免了，把饭钱打赏给我就行，我穷死了。。

**Comment by leoxiaoping** [comment]
@musicode 哈哈，没地方打赏啊，北漂都穷的

**Comment by musicode** [comment]
戳[这里](https://github.com/musicode/react-native-pure-xinge-push#%E6%89%93%E8%B5%8F)

**Comment by musicode** [comment]
我去，大哥你手笔有点大啊

**Comment by musicode** [comment]
@minicase 真是有点感动啊

**Comment by leoxiaoping** [comment]
@musicode 北京请吃顿饭的钱嘛。本来我要自己搞呢，都已经fork一个了开始改了，刚好看到你的了，省了不少时间啊

**Comment by Yunnathai** [comment]
@musicode 亲有联系方式吗

**Comment by musicode** [comment]
@jamninetyfive  打赏参考 readme

**Comment by Yunnathai** [comment]
@musicode 不是 我看你对于封装原生两端sdk比较强，想问问你找不找工作。或者是接不接活儿～

**Comment by musicode** [comment]
接不接活完全看性价比

**Comment by musicode** [comment]
@jamninetyfive 活的信息可以发到我邮箱 musicode@qq.com，我先了解一下哈
