### ISSUE TITLE
register的回调问题

### ISSUE THREAD

**Issue by finalreturn** [musicode/react-native-pure-xinge-push#12]
概述：
第一次安装app并且打开app时，极高概率注册成功并且回调deviceToken。退出app后，后续尝试多次打开app，调用start初始化，会发现无回调信息，多次start后，返回10002，也就是正在注册中，然而很长时间无回调（我大概等待了5分钟，依旧无任何响应）

然后把app的信息清空初始化，大概率又注册成功。
不知道造成这个原因是什么，或是说信鸽的注册是有间隔时间的。

**Comment by musicode** [comment]
这个我就真不知道了，start 我只是拿着传下来的参数去调信鸽的接口，至于成功与否，那就是底层决定的了。

更详细的信息，你可能需要看下信鸽官方开发文档。

> 我只是封装了一个中间层，并没有做啥复杂的事，只是调度顺序方面稍微调了一下。

**Comment by musicode** [comment]
https://xg.qq.com/docs/android_access/android_faq.html
