### ISSUE TITLE
当App进程被杀死时，用户点击系统通知栏的推送进入App，如何在RN中监听到事件

### ISSUE THREAD

**Issue by caigehui** [musicode/react-native-pure-xinge-push#4]
以下代码的事件监听应该只能在App活跃时才能被执行吧？
```
// 推送消息
XingePush.addEventListener('notification', function (notification) {

  // 推送是否弹出展现了
  notification.presented

  // 推送是否被用户点击了
  notification.clicked

  // 自定义的键值对
  notification.custom_content

  // 推送消息主体，安卓没法保证能取到正确的值，最好不要依赖这个字段
  notification.body
})
```

**Comment by musicode** [comment]
如果你是点击通知栏调起 app，这句在 app 启动后，会立即触发，返回的 notification 就是 clicked 为 true

**Comment by finalreturn** [comment]
> 如果你是点击通知栏调起app，这句在app 启动后，会立即触发，返回的notification 就是clicked 为true

每次启动app信鸽注册或多或少的存在延迟，试过多次，通过点击通知栏调起app，并没有触发notification ，导致触发操作失效

**Comment by musicode** [comment]
> > 如果你是点击通知栏调起app，这句在app 启动后，会立即触发，返回的notification 就是clicked 为true
> 
> 每次启动app信鸽注册或多或少的存在延迟，试过多次，通过点击通知栏调起app，并没有触发notification ，导致触发操作失效

需要调用start之后才会触发

**Comment by finalreturn** [comment]
> > > 如果你是点击通知栏调起app，这句在app 启动后，会立即触发，返回的notification 就是clicked 为true
> > 
> > 
> > 每次启动app信鸽注册或多或少的存在延迟，试过多次，通过点击通知栏调起app，并没有触发notification ，导致触发操作失效
> 
> 需要调用start之后才会触发

那就是只能在app活跃状态下调起通知栏 notification才能被触发，
当App进程被杀死时，app启动后因为信鸽还没有完成start，notification的监听是无法起到效果的。
就算完成了start，并且得到register的响应，之前通知栏需要响应的notification也已经没响应了。
还一个就是信鸽调起start，长时间无响应，不知道是信鸽本身服务还是怎么，也就是start失败。

**Comment by musicode** [comment]
我说下我的实现，如果app未启动，此时有推送到达，点击推送会打开app，此时推送信息我会先存着，等你调了start之后再处理，给外部的感觉就像是一个前台状态下接受到的推送。
注意，非活跃状态，js不会执行，这是rn的限制

**Comment by finalreturn** [comment]
> 我说下我的实现，如果app未启动，此时有推送到达，点击推送会打开app，此时推送信息我会先存着，等你调了start之后再处理，给外部的感觉就像是一个前台状态下接受到的推送。
> 注意，非活跃状态，js不会执行，这是rn的限制

sorry，测试了多次，依旧没有达到预期的效果；或者没理解你说的意思；
在打开app时，保存的消息会在我调起start时，是否同时调起notification；我该如何去处理在app杀死的情况下，通过开启厂商通道得到通知，点开进行处理；或者如rn限制一样，无法在js中做到处理

**Comment by musicode** [comment]
1. 调用 start 后，会判断是否为点击推送打开 app，如果是，会触发 notification
2. 厂商通道要先配置信鸽后台，并按 readme 所说，调用对应的 setXXX 方法

如果还不行，可能是我的 bug，我会处理

**Comment by finalreturn** [comment]
> 1. 调用 start 后，会判断是否为点击推送打开 app，如果是，会触发 notification
> 2. 厂商通道要先配置信鸽后台，并按 readme 所说，调用对应的 setXXX 方法
> 
> 如果还不行，可能是我的 bug，我会处理

感谢，还是一样的就是配置厂商了才能在杀死app的情况下得到推送，点击后，开启app后无任何响应，期望能触发notification

**Comment by musicode** [comment]
@finalreturn react-native-pure-xinge-push@0.2.1 修复了

**Comment by finalreturn** [comment]
> @finalreturn react-native-pure-xinge-push@0.2.1 修复了

感谢，另外还发现个问题，我重开个issues吧
