### ISSUE TITLE
iOS缺少podspec

### ISSUE THREAD

**Issue by caigehui** [musicode/react-native-pure-xinge-push#5]
缺少podspec，无法通过cocoapods引入

**Comment by musicode** [comment]
不会这个...

**Comment by caigehui** [comment]
RN@0.60.x是使用auto-linking来添加第三方引用的，我发现在RN的0.60.5版本下iOS不能编译

**Comment by musicode** [comment]
我可能要等10月份才会跟进0.60+，最近比较忙，二是0.60是一次大升级，我要看我的其他库有没有升级，当然了，欢迎 PR

**Comment by musicode** [comment]
发版了 react-native-pure-xinge-push@0.1.6
