### ISSUE TITLE
0.60.5 ios 集成报错  'RNTXingePush/RNTXingePushModule.h' file not found

### ISSUE THREAD

**Issue by charmtiger** [musicode/react-native-pure-xinge-push#7]
步骤是yarn add
pod install
引入 libs
将 libXGSDK.a 引入到 framework

```
AppDelegate.m:17:9: fatal error: 'RNTXingePush/RNTXingePushModule.h' file not found
#import <RNTXingePush/RNTXingePushModule.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by musicode** [comment]
@caigehui 看看咯，你升级的部分是不是有 bug 啊

**Comment by charmtiger** [comment]
补充一下 我注释了 #import <RNTXingePush/RNTXingePushModule.h>
然后就报了如下错误
![image](https://user-images.githubusercontent.com/8412626/64915352-02e36000-d797-11e9-833c-675ac363ef30.png)


![image](https://user-images.githubusercontent.com/8412626/64915320-a7b16d80-d796-11e9-86ff-4e06e5a1ec9b.png)
@caigehui 希望大佬看一下这个问题

**Comment by musicode** [comment]
本来我的计划是十月份中旬以后才可能会升级 0.60，但 @caigehui 提了一个 pr，在我自己升级之前，暂时没有时间处理 pr 带来的 bug（本来就是因为没时间才没升级...）。

@charmtiger 可以先退到 0.59，等我升级之后我再到此 issue 通知你，如果 @caigehui 暂时没空修复 bug，只能先这样了

**Comment by caigehui** [comment]
@charmtiger @musicode 因为RN>=0.60默认是通过cocoapods引入，所以去掉前缀就可以了：

~~#import <RNTXingePush/RNTXingePushModule.h>~~

#import <RNTXingePushModule.h>

**Comment by musicode** [comment]
@caigehui 谢谢~
@charmtiger 试试呗，没问题就关掉 issue 吧

**Comment by charmtiger** [comment]
经过尝试还是报错
![image](https://user-images.githubusercontent.com/8412626/65061066-b4f37580-d9ab-11e9-9f12-4bbc8f1cbe69.png)
@caigehui 

补充一下我的library引入
![image](https://user-images.githubusercontent.com/8412626/65061158-ec622200-d9ab-11e9-9909-5680fc6aef54.png)

**Comment by caigehui** [comment]
@charmtiger 报错是因为没找到信鸽的sdk，可尝试：
1. 引入的时候选`create groups`而不是`create folder references`，建议直接加入到`ios`目录下
2. 先`clean`一下再`build`
3. 新建一个工程来引入该库，测试是否可行，因为我这里都是在新工程中测试的

最后如果实在不行，可提供一个能复现问题的仓库，我来看看是什么原因

**Comment by charmtiger** [comment]
问题已解决 
原因就是： 引入的时候选create groups而不是create folder references

**Comment by musicode** [comment]
最新版不用自己添加库了，yarn add 完直接 cd ios && pod install 就完事
